name: CI - Run tests
on: [push]


jobs:
    test:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - name: Set up Python
        uses: actions/setup-python@v4
        with:
            python-version: '25.3'
        - name: Install dependencies
          run: |
            python.exe -m pip install --upgrade pip
            pip install -r requirements.txt
        - name: Run tests
          run: |
            pytest --maxfail=1 -q
        - name: Upload report
        uses: actions/upload-artifact@v4
        with:
            name: pytest-report
            path: reports/